### ISSUE TITLE
Add test files to existing algorithms

### ISSUE THREAD

**Issue by sashrika15** [sashrika15/Unsupervised_Learning_Algorithms#12]
Some older contributions do not have test files, create test files for them.

Respond to this issue to be assigned. Please comment the name and category of the algorithm you are adding the test file for.

**Comment by srijarkoroy** [comment]
Algorithm chosen: Independent Component Analysis
Category: component_analysis

**Comment by srijarkoroy** [comment]
Algorithm chosen: K-Means
Category: Clustering

**Comment by indiradutta** [comment]
Algorithm chosen: PCA
Category: component_analysis
Add test.py and source code

**Comment by aryankargwal** [comment]
Algorithm Chosen: BIRCH Clustering

**Comment by Pranav1007** [comment]
Algorithm Chosen: SOMs
Category: Clustering

**Comment by sashrika15** [comment]
> Algorithm Chosen: SOMs
> Category: Clustering

Hey Pranav, could you also change your folder name to just SOM

**Comment by sashrika15** [comment]
All old algorithms have been updated! Great work everyone
