### ISSUE TITLE
[Docs] Lack of Readability in GMM's page

### ISSUE THREAD

**Issue by AlKun25** [sashrika15/Unsupervised_Learning_Algorithms#22]
_A lot of GitHub users prefer to use the dark theme._

There was a particular issue with the [GMM's README.md](https://github.com/sashrika15/Unsupervised_Learning_Algorithms/tree/master/clustering/GMM)
- The formula added in the README cannot be seen when the user is in **dark mode**. It is completely indistinguishable.

Possible solutions:
 - [x] Adding an image of the formula, with _white_ background for better readability.
 - [x] Change to set the background color in the LATEX code(if used)

**Comment by AlKun25** [comment]
Would like to contribute in easiest way possible XD

**Comment by sashrika15** [comment]
Go ahead!
